steps:
  # Step 1: Simple test step
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        pip install --upgrade pip
        pip install pytest flask
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        echo "Running syntax check..."
        python -c "import sys; print('Python version:', sys.version)"
        find . -name "*.py" -exec python -m py_compile {} \;
        echo "Basic tests completed successfully"
    id: 'test'

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/sit707-cicd-project-123456/python-cicd-app:latest'
      - '.'
    id: 'build'
    waitFor: ['test']

  # Step 3: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sit707-cicd-project-123456/python-cicd-app:latest']
    id: 'push'
    waitFor: ['build']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'python-cicd-app'
      - '--image'
      - 'gcr.io/sit707-cicd-project-123456/python-cicd-app:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
    id: 'deploy'
    waitFor: ['push']

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'

images:
  - 'gcr.io/sit707-cicd-project-123456/python-cicd-app:latest'